### ISSUE TITLE
CMake errors in Boost.Filesystem CI

### ISSUE THREAD

**Issue by Lastique** [boostorg/cmake#10]
It seems, something in Boost.CMake was changed recently that caused CI failures in Boost.Filesystem:

```
CMake Error: install(EXPORT "boost_move-targets" ...) includes target "boost_move" which requires target "boost_assert" that is not in the export set.
CMake Error: install(EXPORT "boost_move-targets" ...) includes target "boost_move" which requires target "boost_core" that is not in the export set.
```

https://travis-ci.org/github/boostorg/filesystem/jobs/774080073

The test `libs/filesystem/test/test_cmake` uses Boost.CMake to define CMake targets for all libraries, which is where, it looks like, CMake fails. At least `install()` is not used in Boost.Filesystem.

**Comment by pdimov** [comment]
It requires this commit https://github.com/boostorg/move/commit/283d36c0b580f4a886239e89a19910f06d0dbff4 and should fix itself when @igaztanaga merges Move to master. There were too many non-CMake-related changes in develop so I didn't want to do it, and it didn't seem necessary to cherry-pick.

**Comment by pdimov** [comment]
Although it looks like I'll have to cherry-pick it, because too many CI things are now failing for me too. :-)

**Comment by pdimov** [comment]
Done.

**Comment by Lastique** [comment]
Thanks!
