### ISSUE TITLE
gcc 9.3   boost1.76  cmake3.20   not build

### ISSUE THREAD

**Issue by xmlgrg** [boostorg/cmake#11]
[root@localhost build]# sudo cmake -DCMAKE_INSTALL_PREFIX="/xmlgrg/518" -DBOOST_ROOT=/xmlgrg/518/ -DCMAKE_PREFIX_PATH="/xmlgrg/518" -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 9.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-9/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (include):
  include could not find requested file:

    BoostRoot

-- Configuring incomplete, errors occurred!
See also "/xmlgrg/517/src/boost-master/build/CMakeFiles/CMakeOutput.log".

**Comment by pdimov** [comment]
Building with CMake is still experimental and won't yet work for most of Boost. That said, you don't seem to have cloned the Boost submodules.

**Comment by xmlgrg** [comment]
ok
