### ISSUE TITLE
Shouldn't boost headers be marked as system in CMake config?

### ISSUE THREAD

**Issue by ixSci** [boostorg/cmake#21]
Right now every boost target provides its headers by setting the following property: `INTERFACE_INCLUDE_DIRECTORIES`. And there is another property: `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES` which, I think, should be used as well. I don't know if that should be default or not but I believe it should at least be supported so users can opt-in on boost library being treated as system.

**Comment by jzakrzewski** [comment]
Compilers do not care about the timestamps.
For other tool (like ninja) I don't believe it analyzes whether one passes -I/path/to/headers or -isystem /path/to/headers...

**Comment by tastyherring** [comment]
Marking boosts header as system will allow users to increase the compiler warning level for their projects code and not get flood with warnings cause by boost system headers.  This would be very useful.

**Comment by pdimov** [comment]
IMPORTED targets always use SYSTEM for their includes by default, even for the INTERFACE_INCLUDE_DIRECTORIES property.

See https://cmake.org/cmake/help/latest/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html

**Comment by ixSci** [comment]
> IMPORTED targets always use SYSTEM for their includes by default, even for the INTERFACE_INCLUDE_DIRECTORIES property.
> 
> See https://cmake.org/cmake/help/latest/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html

Very good find, thank you! So this issue makes no sense and should be closed, then. Nice of CMake to have this information buried somewhere you can't easily find  but what can you do.
