### ISSUE TITLE
find_package(boost COMPONENTS <long_list> CONFIG) is slow and can run out of stack space

### ISSUE THREAD

**Issue by Neumann-A** [boostorg/cmake#40]
In generell the generated cmake config files do recursive lookup of already look up boost modules which will need to excessive nesting and can even make CMake run out of stack space. I simply added a guard around the generated `find_dependency(boost_<module>)` calls so that it generates i.e.:

 ```
 if(NOT boost_<module>_FOUND)
   find_dependency(boost_<module>)
endif()
 ```
 
 This significantly speed up `find_package(boost COMPONENTS <long_list> CONFIG)` calls.

**Comment by pdimov** [comment]
Fixed by https://github.com/boostorg/cmake/pull/43.
