### ISSUE TITLE
No possibility to use CMake FetchContent

### ISSUE THREAD

**Issue by adamvm** [boostorg/cmake#6]
Currently it is not possible to use FetchContent module/functions of CMake.

**Comment by pdimov** [comment]
Since Boost's support for CMake is still experimental, it's intentionally disabled by default. To enable it, add `set(BOOST_ENABLE_CMAKE ON)` to your CMakeLists.txt file, somewhere before the `add_subdirectory` call.

**Comment by excitoon** [comment]
@pdimov @brendoncdrew I tried this:
```
set (BOOST_ENABLE_CMAKE ON)
FetchContent_Declare (boost URL "https://github.com/boostorg/boost/archive/da041154c6bac1a4aa98254a7d6819059e8ac0b0.zip")
FetchContent_MakeAvailable (boost)
```

It gives:
```
CMake Error at /home/vladimir/some-project-bin/_deps/boost-src/CMakeLists.txt:20 (include):
  include could not find load file:

    BoostRoot


-- Configuring incomplete, errors occurred!
See also "/home/vladimir/some-project-bin/CMakeFiles/CMakeOutput.log".
```

Any suggestions?

**Comment by excitoon** [comment]
I see, I should have selected release sources, not sources sources :)
![Screenshot from 2023-02-02 18-16-18](https://user-images.githubusercontent.com/2255111/216364710-4adcefad-2894-4280-be91-1ddd5d2dc1fa.png)

**Comment by excitoon** [comment]
It successfully compiles without any problem on random i686 MinGW cross-compilation environment. I greatly appreciate your work @pdimov .

**Comment by felixf4xu** [comment]
>  should have selected release sources, not sources sources :)

please also note that this should be from **release** not **tag**, file size is very different!!

>[boost-1.82.0.7z](https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.7z)
88.5 MB
Apr 14
[boost-1.82.0.tar.gz](https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.tar.gz)
116 MB
Apr 14
[boost-1.82.0.tar.xz](https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.tar.xz)
88.2 MB
Apr 14
[boost-1.82.0.zip](https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.zip)
147 MB
Apr 14
Source code
(zip)
Apr 6
Source code
(tar.gz)
Apr 6

**Comment by melroy89** [comment]
Here is an example how to use it, it doesn't seem to be documented well enough IMO:

```cmake
set(BOOST_INCLUDE_LIBRARIES asio regex algorithm)
set(BOOST_ENABLE_CMAKE ON)
FetchContent_Declare(
  Boost
  URL https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.7z
  USES_TERMINAL_DOWNLOAD TRUE
  DOWNLOAD_NO_EXTRACT FALSE
)
FetchContent_MakeAvailable(Boost)
```

Then link the library you want to the target (exampe: `your_target`);

```cmake
target_link_libraries(your_target Boost::asio)
```

Maybe this helps somebody.

**Comment by pdimov** [comment]
It's documented [here](https://github.com/boostorg/cmake#using-boost-with-fetchcontent).

**Comment by melroy89** [comment]
> It's documented [here](https://github.com/boostorg/cmake#using-boost-with-fetchcontent).

Yes true sorry, it was not explained on the official boostorg/boost repo is what I meant. OK, I understand you want to keep that clean.

What about `DOWNLOAD_NO_EXTRACT FALSE`? Could that speed up some what? I switched from 7z to tar.xz now. Maybe is there more speed to gain somehow?

**Comment by pdimov** [comment]
7z and tar.xz should be about the same. I can't think of any way to speed that up, sorry. It's still a 90MB download in any case.

**Comment by melroy89** [comment]
Instead of a mono-repo maybe it's a good idea to split the repo in smaller chunks, I only wish to use asio and regex basically. Just thinking out loud here, since the repo size and the artifacts in general are getting bigger and bigger over time. At least not smaller ;)

**Comment by pdimov** [comment]
You can clone from Github instead of downloading the release archive. This is usually much slower, but if you only need a few submodules, it could be faster. Something like

```
FetchContent_Declare(
  Boost
  GIT_REPOSITORY https://github.com/boostorg/boost.git
  GIT_TAG boost-1.84.0
  GIT_SUBMODULES asio regex
)
```
but that's not going to work because you'll also need the dependencies of Asio, which at present are...
```
C:\boost-git\develop>dist\bin\boostdep --brief asio
Brief dependency report for asio (sources on, tests off):

# Primary dependencies

align
assert
config
context
coroutine
date_time
system
throw_exception

# Secondary dependencies

core
static_assert
mp11
pool
predef
smart_ptr
exception
move
type_traits
utility
algorithm
io
lexical_cast
numeric~conversion
range
tokenizer
winapi
variant2
array
bind
concept_check
function
iterator
mpl
regex
tuple
unordered
container
integer
conversion
preprocessor
container_hash
detail
optional
intrusive
describe
function_types
fusion
functional
typeof
```

Sorry. :-)

**Comment by melroy89** [comment]
No worries. Dependency graph:

![depedencies](https://github.com/boostorg/cmake/assets/628926/37c536b7-d559-40c0-97c6-0e669b8c95a2)

**Comment by melroy89** [comment]
> You can clone from Github instead of downloading the release archive. This is usually much slower, but if you only need a few submodules, it could be faster. Something like
> 
> ```
> FetchContent_Declare(
>   Boost
>   GIT_REPOSITORY https://github.com/boostorg/boost.git
>   GIT_TAG boost-1.84.0
>   GIT_SUBMODULES asio regex
> )
> ```
> 
> but that's not going to work because you'll also need the dependencies of Asio, which at present are...
> 
> ```
> C:\boost-git\develop>dist\bin\boostdep --brief asio
> Brief dependency report for asio (sources on, tests off):
> 
> # Primary dependencies
> 
> align
> assert
> config
> context
> coroutine
> date_time
> system
> throw_exception
> 
> # Secondary dependencies
> 
> core
> static_assert
> mp11
> pool
> predef
> smart_ptr
> exception
> move
> type_traits
> utility
> algorithm
> io
> lexical_cast
> numeric~conversion
> range
> tokenizer
> winapi
> variant2
> array
> bind
> concept_check
> function
> iterator
> mpl
> regex
> tuple
> unordered
> container
> integer
> conversion
> preprocessor
> container_hash
> detail
> optional
> intrusive
> describe
> function_types
> fusion
> functional
> typeof
> ```
> 
> Sorry. :-)

I actually just found out that Asio is a separate library, which doesn't need Boost: https://github.com/chriskohlhoff/asio/
