### ISSUE TITLE
Shared and Static variant cannot coexist in installation prefix on Windows

### ISSUE THREAD

**Issue by sodevel** [boostorg/cmake#62]
I used to build Boost with `b2` but since this is currently not working with Visual Studio 2022 17.10 i discovered there is a CMake build available since some time. I used to build 4 variants on Windows, Debug and Release as Static and DLL, and installed them in the same target location, this was working without problems. However, this doesn't work when using CMake.

I am building Boost like this:

```cmd
cmake -S . -B "build-cmake-%LIBRARY_TARGET%-dll" -G "Ninja Multi-Config" -DCMAKE_INSTALL_PREFIX="%LIBRARY_INSTALL_PREFIX%" -DBOOST_INSTALL_LAYOUT=versioned -DBUILD_SHARED_LIBS=ON -DBOOST_RUNTIME_LINK=shared

...

cmake -S . -B "build-cmake-%LIBRARY_TARGET%-static" -G "Ninja Multi-Config" -DCMAKE_INSTALL_PREFIX="%LIBRARY_INSTALL_PREFIX%" -DBOOST_INSTALL_LAYOUT=versioned -DBUILD_SHARED_LIBS=OFF -DBOOST_RUNTIME_LINK=shared
```

While the libraries themself still do coexist, the CMake target configurations get overwritten. In the example above, only the static targets are present, the DLL targets are gone.

**Comment by pdimov** [comment]
CMake doesn't have a good answer for the question of installing both shared and static variants of a library.

I suppose the best you could do today is install the CMake config files into two separate directories, one for static, one for shared, by setting BOOST_INSTALL_CMAKEDIR.

Since they define the same targets, they can't go into the same directory anyway.

**Comment by pdimov** [comment]
Yeah, I looked at the `find_package` search paths and there's no good way to put the shared/static configs in separate BOOST_INSTALL_CMAKEDIRs and have them be found automatically (without setting the path explicitly in the CMakeLists.txt file.)

Whereas appending -shared or -static to the subdirectory works out of the box and seems to be backward-compatible in that existing uses will still work.

**Comment by pdimov** [comment]
I've implemented this on the develop branch.

**Comment by sodevel** [comment]
Thank you very much for addressing this so quickly. I just tested your implementation, sadly it's not fully working. I found the cause but cannot fix it myself, i'm hitting following error:

```
[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
[cmake]   Could not find a configuration file for package "boost_exception" that
[cmake]   exactly matches requested version "1.86.0".
[cmake] 
[cmake]   The following configuration files were considered but not accepted:
[cmake] 
[cmake]     C:/devel/cmake/msvc/14.3/x86/boost/boost-1.71.0.beta1-3435-gbe6765ef52-dirty/lib/cmake/boost_exception-1.86.0-static/boost_exception-config.cmake, version: 1.86.0 (static)
[cmake] 
[cmake] Call Stack (most recent call first):
[cmake]   C:/devel/cmake/msvc/14.3/x86/boost/boost-1.71.0.beta1-3435-gbe6765ef52-dirty/lib/cmake/boost_coroutine-1.86.0-shared/boost_coroutine-config.cmake:22 (find_dependency)
[cmake]   C:/devel/cmake/msvc/14.3/x86/boost/boost-1.71.0.beta1-3435-gbe6765ef52-dirty/lib/cmake/Boost-1.86.0/BoostConfig.cmake:67 (find_package)
[cmake]   C:/devel/cmake/msvc/14.3/x86/boost/boost-1.71.0.beta1-3435-gbe6765ef52-dirty/lib/cmake/Boost-1.86.0/BoostConfig.cmake:128 (boostcfg_find_component)
[cmake]   C:/Program Files/CMake/share/cmake-3.29/Modules/FindBoost.cmake:594 (find_package)
[cmake]   CMakeLists.txt:37 (find_package)
[cmake] 
```

In my build the library `boost_exception` is together with `boost_test_exec_monitor` the only library that exists only in a static version. I checked a `b2` build of boost, it looks like `boost_exception` is empty, i haven't found a location where this library does get added to the target. For `boost_test_exec_monitor` in both cases the static library gets added to the target.

It looks like these two libraries need a special handling.

**Comment by pdimov** [comment]
Yes, `boost_exception` is hardcoded to static. I'll look into that.

**Comment by pdimov** [comment]
Should be fixed now.

**Comment by sodevel** [comment]
Thanks, it is working flawless for me now.
