### ISSUE TITLE
heap do not appear in built include

### ISSUE THREAD

**Issue by biggiantpigeon** [boostorg/cmake#70]
Hello, I'm trying to use cmake to build boost, further use it in my ownproject. Then I find module heap although pulled as submodule in `libs`, but not appear in `include` folder after my build and install. I can sure copy it from your released pre-built version, but I want to solve this in an elegant way. Any suggestions?

**Comment by pdimov** [comment]
What Boost version?

**Comment by biggiantpigeon** [comment]
> What Boost version?

1.82.0

**Comment by pdimov** [comment]
Does the issue still persist in newer versions, such as for instance 1.85.0?

**Comment by pdimov** [comment]
How does your project use Boost? Do you use CMake to build and install Boost first, or do you build Boost as a subproject, using `add_subdirectory`?

**Comment by biggiantpigeon** [comment]
> Does the issue still persist in newer versions, such as for instance 1.85.0?

I'll tried, it's the same for 1.85.0.

> How does your project use Boost? Do you use CMake to build and install Boost first, or do you build Boost as a subproject, using `add_subdirectory`?
I did the 'build and install' first.

**Comment by pdimov** [comment]
You would need to add `heap` to the list if you need it to be installed.

**Comment by biggiantpigeon** [comment]
yes, it works now, thanks a lot.
